version: '3.3'
services:
  oraclixbotdev:
    container_name: oraclixBotDev
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run development
